### ISSUE TITLE
About resume

### ISSUE THREAD

**Issue by philokey** [roytseng-tw/Detectron.pytorch#37] opened 2018-05-03 15:27 UTC
Hello,  I  try to resume the training by using this command:

```
 python tools/train_net_step.py --dataset coco2017 --cfg configs/e2e_faster_rcnn_R-101-FPN_1x.yaml --use_tfboard --load_ckpt  Outputs/e2e_faster_rcnn_R-101-FPN_1x/May02-12-15-12_faster_step/ckpt/model_step69999.pth --resume
```

However,  it throw out a runtime error

```
Traceback (most recent call last):
  File "tools/train_net_step.py", line 367, in main
    optimizer.step()
  File "/home/philokey/.virtualenvs/py3/lib/python3.5/site-packages/torch/optim/sgd.py", line 94, in step
    buf.mul_(momentum).add_(1 - dampening, d_p)
RuntimeError: invalid argument 3: sizes do not match at /pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:271

```

How can I solve this problem?

**Comment by roytseng-tw** [comment] 2018-05-04 04:29
Have you changed anything ? I can't reproduce this error myself.

**Comment by roytseng-tw** [comment] 2018-05-04 06:16
I have test with res101 and everything works fine. BTW, what's your pytorch version ?

**Comment by roytseng-tw** [comment] 2018-05-04 07:50
Maybe you could send me a link to download your checkpoint. And I'll test it.

**Comment by philokey** [comment] 2018-05-04 15:00
Thank you very much.
I upload my checkpoint to [here](https://drive.google.com/drive/folders/1gO3n6rDM67bMP-5nCWBbwhr3oeKGPOUM?usp=sharing).

**Comment by roytseng-tw** [comment] 2018-05-04 16:35
Hi, the way that pytorch store the optimizer states is not really robust. If the order of params in param_groups changed, then the state relating to params will not be restored in the correct correspondence, and thus results in the size mismatch error above. Not sure if this problem has been improved in pytorch 0.4 or not.

You must have updated (git pull) the code between the training and resume, and the order of params  in param_groups is changed.

**Comment by roytseng-tw** [comment] 2018-05-04 16:55
I'll take a remedy for that.

**Comment by roytseng-tw** [comment] 2018-05-05 02:33
Interestingly, I found that the order of param ids in the checkpoint `ckpt['optimizer'][['param_groups'][i]['params']` is not changed. When I try to match the shape of params in `ckpt['model']` and momentum_buffers in `ckpt['optimizer']['state'][param_id]['momentum_buffer']`, using the fact that model state_dict (parameters) is insertion ordered, I found those shapes do not match. So your checkpoint seems corrupted somehow.

Are you facing the same issue, if you restart a new training and then try to resume from any of the new checkpoints ? (BTW, press ctrl+c to terminate the program will also save a checkpoint)

**Comment by roytseng-tw** [comment] 2018-05-05 14:46
What's you pytorch version? It's recommend to use 0.3.1 for now.

**Comment by philokey** [comment] 2018-05-05 15:29
I use 0.3.1 & ubuntu 16.04 & titan xp & python3.5

**Comment by roytseng-tw** [comment] 2018-05-06 00:32
Are you still facing the same issue now, or it's solved after retraining ?

**Comment by philokey** [comment] 2018-05-06 01:38
Unfortunately, I still facing the same issue after retraining：param and momentum_buffer shape mismatch in checkpoint

**Comment by roytseng-tw** [comment] 2018-05-06 03:05
I may not able to help with your any further.

Here are some suggestions:
1. Record the actually mapping of param name and param id to see if the saved optimizer checkpoint is really wrong.
2. Try doing the same thing, loading a optimizer checkpoint, in other pytorch projects.

Closing the issue since it's not a bug related to this project. Feel free to open it again if you found it is !

**Closed by roytseng-tw** 2018-05-06 03:05 UTC

**Comment by luohuan2uestc** [comment] 2018-05-29 02:26
@philokey i have facing the same problems? 
have you solve this problem?
thx!

**Comment by choasup** [comment] 2018-12-17 13:07
https://github.com/choasup/pytorch-fasterRCNN/issues/1#issuecomment-447836926
